### ISSUE TITLE
BetterSchool defaults to monday of current week

### ISSUE THREAD

**Issue by Velkee** [CheesyPhoenix/BetterSchool#1] opened 2022-08-21 16:44 UTC
When opening the app the calendar will default to showing Monday of the current week. It would probably be better if the app shows the current day, or at least switches forward to the next week after Friday

**Comment by CheesyPhoenix** [comment] 2022-08-28 13:36
Thought i'd fixed this, but apparently i have not

**Comment by CheesyPhoenix** [comment] 2022-09-01 08:38
caused by a bug in the api. Fixed now

**Closed as completed by CheesyPhoenix** 2022-09-01 08:38 UTC
Labels: enhancement
